<?php

use App\Http\Controllers\AuthController;
use App\Http\Controllers\ActivityController;
use App\Http\Controllers\ActivityLogController;
use App\Http\Controllers\AlbumController;
use App\Http\Controllers\AnnualFeeController;
use App\Http\Controllers\AxeController;
use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\CashCategoryController;
use App\Http\Controllers\CashTransactionController;
use App\Http\Controllers\ContactAdminController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DonationController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\EducationLevelController;
use App\Http\Controllers\FeePaymentController;
use App\Http\Controllers\FunctionController;
use App\Http\Controllers\GroupMessageController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\MembershipCardController;
use App\Http\Controllers\MaterialController;
use App\Http\Controllers\MaterialLoanController;
use App\Http\Controllers\MaterialMaintenanceController;
use App\Http\Controllers\MaterialMovementController;
use App\Http\Controllers\MemberApplicationController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SlideController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\StatuteArticleController;
use App\Http\Controllers\StatuteController;
use App\Http\Controllers\StatuteTitleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WebsiteController;
use Illuminate\Support\Facades\Route;

Route::prefix('auth')->group(function () {
    Route::post('/register', [AuthController::class, 'register'])->name('auth.register');
    Route::post('/login', [AuthController::class, 'login'])->name('auth.login');
    Route::post('/forgot-password', [AuthController::class, 'forgotPassword'])->name('auth.forgot_password');
    Route::post('/forgot-password/verify-code', [AuthController::class, 'verifyResetCode'])->name('auth.forgot_password.verify_code');
    Route::post('/reset-password', [AuthController::class, 'resetPassword'])->name('auth.reset_password');
});

Route::get('/website/home', [WebsiteController::class, 'homeData'])->name('website.home');
Route::get('/website/about', [WebsiteController::class, 'aboutData'])->name('website.about');
Route::get('/website/gallery', [WebsiteController::class, 'galleryData'])->name('website.gallery');
Route::get('/website/activities', [WebsiteController::class, 'activitiesData'])->name('website.activities');
Route::get('/website/member-application-meta', [MemberApplicationController::class, 'publicMeta'])->name('website.member_application_meta');
Route::post('/member-applications', [MemberApplicationController::class, 'store'])->name('member_applications.store');
Route::post('/contact-us', [ContactUsController::class, 'store'])->name('contact_us.store');

Route::middleware('auth:sanctum')->group(function () {
    Route::prefix('auth')->group(function () {
        Route::get('/me', [AuthController::class, 'me'])->name('auth.me');
        Route::put('/me', [AuthController::class, 'updateProfile'])->name('auth.me.update');
        Route::post('/logout', [AuthController::class, 'logout'])->name('auth.logout');
    });

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard.index');
    Route::get('/users', [UserController::class, 'index'])->name('users.index');
    Route::post('/users', [UserController::class, 'store'])->name('users.store');
    Route::get('/users/{encryptedId}', [UserController::class, 'show'])->name('users.show');
    Route::put('/users/{encryptedId}', [UserController::class, 'update'])->name('users.update');
    Route::delete('/users/{encryptedId}', [UserController::class, 'destroy'])->name('users.destroy');
    Route::post('/users/{encryptedId}/roles/assign', [UserController::class, 'assignRole'])->name('users.roles.assign');
    Route::post('/users/{encryptedId}/roles/remove', [UserController::class, 'removeRole'])->name('users.roles.remove');
    Route::put('/users/{encryptedId}/roles/sync', [UserController::class, 'syncRoles'])->name('users.roles.sync');
    Route::get('/activity-logs', [ActivityLogController::class, 'index'])->name('activity_logs.index');
    Route::get('/activity-logs/{id}', [ActivityLogController::class, 'show'])->name('activity_logs.show');
    Route::get('/activities', [ActivityController::class, 'index'])->name('activities.index');
    Route::post('/activities', [ActivityController::class, 'store'])->name('activities.store');
    Route::get('/activities/{encryptedId}', [ActivityController::class, 'show'])->name('activities.show');
    Route::put('/activities/{encryptedId}', [ActivityController::class, 'update'])->name('activities.update');
    Route::delete('/activities/{encryptedId}', [ActivityController::class, 'destroy'])->name('activities.destroy');
    Route::get('/albums', [AlbumController::class, 'index'])->name('albums.index');
    Route::post('/albums', [AlbumController::class, 'store'])->name('albums.store');
    Route::get('/albums/{encryptedId}', [AlbumController::class, 'show'])->name('albums.show');
    Route::put('/albums/{encryptedId}', [AlbumController::class, 'update'])->name('albums.update');
    Route::delete('/albums/{encryptedId}', [AlbumController::class, 'destroy'])->name('albums.destroy');
    Route::get('/annual-fees', [AnnualFeeController::class, 'index'])->name('annual_fees.index');
    Route::post('/annual-fees', [AnnualFeeController::class, 'store'])->name('annual_fees.store');
    Route::get('/annual-fees/{encryptedId}', [AnnualFeeController::class, 'show'])->name('annual_fees.show');
    Route::put('/annual-fees/{encryptedId}', [AnnualFeeController::class, 'update'])->name('annual_fees.update');
    Route::delete('/annual-fees/{encryptedId}', [AnnualFeeController::class, 'destroy'])->name('annual_fees.destroy');
    Route::get('/axes', [AxeController::class, 'index'])->name('axes.index');
    Route::post('/axes', [AxeController::class, 'store'])->name('axes.store');
    Route::get('/axes/{encryptedId}', [AxeController::class, 'show'])->name('axes.show');
    Route::put('/axes/{encryptedId}', [AxeController::class, 'update'])->name('axes.update');
    Route::delete('/axes/{encryptedId}', [AxeController::class, 'destroy'])->name('axes.destroy');
    Route::get('/education-levels', [EducationLevelController::class, 'index'])->name('education_levels.index');
    Route::post('/education-levels', [EducationLevelController::class, 'store'])->name('education_levels.store');
    Route::get('/education-levels/{encryptedId}', [EducationLevelController::class, 'show'])->name('education_levels.show');
    Route::put('/education-levels/{encryptedId}', [EducationLevelController::class, 'update'])->name('education_levels.update');
    Route::delete('/education-levels/{encryptedId}', [EducationLevelController::class, 'destroy'])->name('education_levels.destroy');
    Route::get('/functions', [FunctionController::class, 'index'])->name('functions.index');
    Route::post('/functions', [FunctionController::class, 'store'])->name('functions.store');
    Route::get('/functions/{encryptedId}', [FunctionController::class, 'show'])->name('functions.show');
    Route::put('/functions/{encryptedId}', [FunctionController::class, 'update'])->name('functions.update');
    Route::delete('/functions/{encryptedId}', [FunctionController::class, 'destroy'])->name('functions.destroy');
    Route::get('/members', [MemberController::class, 'index'])->name('members.index');
    Route::get('/group-messages', [GroupMessageController::class, 'index'])->name('group_messages.index');
    Route::post('/group-messages', [GroupMessageController::class, 'store'])->name('group_messages.store');
    Route::get('/group-messages/{encryptedId}', [GroupMessageController::class, 'show'])->name('group_messages.show');
    Route::delete('/group-messages/{encryptedId}', [GroupMessageController::class, 'destroy'])->name('group_messages.destroy');
    Route::get('/member-applications', [MemberApplicationController::class, 'index'])->name('member_applications.index');
    Route::get('/member-applications/{encryptedId}', [MemberApplicationController::class, 'show'])->name('member_applications.show');
    Route::post('/member-applications/{encryptedId}/review', [MemberApplicationController::class, 'review'])->name('member_applications.review');
    Route::post('/members', [MemberController::class, 'store'])->name('members.store');
    Route::get('/members/{encryptedId}', [MemberController::class, 'show'])->name('members.show');
    Route::put('/members/{encryptedId}', [MemberController::class, 'update'])->name('members.update');
    Route::delete('/members/{encryptedId}', [MemberController::class, 'destroy'])->name('members.destroy');
    Route::get('/reports', [ReportController::class, 'index'])->name('reports.index');
    Route::post('/reports', [ReportController::class, 'store'])->name('reports.store');
    Route::get('/reports/{encryptedId}', [ReportController::class, 'show'])->name('reports.show');
    Route::put('/reports/{encryptedId}', [ReportController::class, 'update'])->name('reports.update');
    Route::post('/reports/{encryptedId}/scan-attendance', [ReportController::class, 'scanAttendance'])->name('reports.scan_attendance');
    Route::delete('/reports/{encryptedId}', [ReportController::class, 'destroy'])->name('reports.destroy');
    Route::get('/membership-cards', [MembershipCardController::class, 'index'])->name('membership_cards.index');
    Route::post('/membership-cards', [MembershipCardController::class, 'store'])->name('membership_cards.store');
    Route::get('/membership-cards/{encryptedId}', [MembershipCardController::class, 'show'])->name('membership_cards.show');
    Route::put('/membership-cards/{encryptedId}', [MembershipCardController::class, 'update'])->name('membership_cards.update');
    Route::delete('/membership-cards/{encryptedId}', [MembershipCardController::class, 'destroy'])->name('membership_cards.destroy');
    Route::get('/materials', [MaterialController::class, 'index'])->name('materials.index');
    Route::post('/materials', [MaterialController::class, 'store'])->name('materials.store');
    Route::get('/materials/{encryptedId}', [MaterialController::class, 'show'])->name('materials.show');
    Route::put('/materials/{encryptedId}', [MaterialController::class, 'update'])->name('materials.update');
    Route::delete('/materials/{encryptedId}', [MaterialController::class, 'destroy'])->name('materials.destroy');
    Route::get('/material-loans', [MaterialLoanController::class, 'index'])->name('material_loans.index');
    Route::post('/material-loans', [MaterialLoanController::class, 'store'])->name('material_loans.store');
    Route::get('/material-loans/{encryptedId}', [MaterialLoanController::class, 'show'])->name('material_loans.show');
    Route::put('/material-loans/{encryptedId}', [MaterialLoanController::class, 'update'])->name('material_loans.update');
    Route::post('/material-loans/{encryptedId}/return', [MaterialLoanController::class, 'returnLoan'])->name('material_loans.return');
    Route::delete('/material-loans/{encryptedId}', [MaterialLoanController::class, 'destroy'])->name('material_loans.destroy');
    Route::get('/material-maintenances', [MaterialMaintenanceController::class, 'index'])->name('material_maintenances.index');
    Route::post('/material-maintenances', [MaterialMaintenanceController::class, 'store'])->name('material_maintenances.store');
    Route::get('/material-maintenances/{encryptedId}', [MaterialMaintenanceController::class, 'show'])->name('material_maintenances.show');
    Route::put('/material-maintenances/{encryptedId}', [MaterialMaintenanceController::class, 'update'])->name('material_maintenances.update');
    Route::delete('/material-maintenances/{encryptedId}', [MaterialMaintenanceController::class, 'destroy'])->name('material_maintenances.destroy');
    Route::get('/material-movements', [MaterialMovementController::class, 'index'])->name('material_movements.index');
    Route::post('/material-movements', [MaterialMovementController::class, 'store'])->name('material_movements.store');
    Route::get('/material-movements/{encryptedId}', [MaterialMovementController::class, 'show'])->name('material_movements.show');
    Route::put('/material-movements/{encryptedId}', [MaterialMovementController::class, 'update'])->name('material_movements.update');
    Route::delete('/material-movements/{encryptedId}', [MaterialMovementController::class, 'destroy'])->name('material_movements.destroy');
    Route::get('/slides', [SlideController::class, 'index'])->name('slides.index');
    Route::post('/slides', [SlideController::class, 'store'])->name('slides.store');
    Route::get('/slides/{encryptedId}', [SlideController::class, 'show'])->name('slides.show');
    Route::put('/slides/{encryptedId}', [SlideController::class, 'update'])->name('slides.update');
    Route::delete('/slides/{encryptedId}', [SlideController::class, 'destroy'])->name('slides.destroy');
    Route::get('/suppliers', [SupplierController::class, 'index'])->name('suppliers.index');
    Route::post('/suppliers', [SupplierController::class, 'store'])->name('suppliers.store');
    Route::get('/suppliers/{encryptedId}', [SupplierController::class, 'show'])->name('suppliers.show');
    Route::put('/suppliers/{encryptedId}', [SupplierController::class, 'update'])->name('suppliers.update');
    Route::delete('/suppliers/{encryptedId}', [SupplierController::class, 'destroy'])->name('suppliers.destroy');
    Route::get('/cash-categories', [CashCategoryController::class, 'index'])->name('cash_categories.index');
    Route::post('/cash-categories', [CashCategoryController::class, 'store'])->name('cash_categories.store');
    Route::get('/cash-categories/{encryptedId}', [CashCategoryController::class, 'show'])->name('cash_categories.show');
    Route::put('/cash-categories/{encryptedId}', [CashCategoryController::class, 'update'])->name('cash_categories.update');
    Route::delete('/cash-categories/{encryptedId}', [CashCategoryController::class, 'destroy'])->name('cash_categories.destroy');
    Route::get('/cash-transactions', [CashTransactionController::class, 'index'])->name('cash_transactions.index');
    Route::post('/cash-transactions', [CashTransactionController::class, 'store'])->name('cash_transactions.store');
    Route::get('/cash-transactions/{encryptedId}', [CashTransactionController::class, 'show'])->name('cash_transactions.show');
    Route::put('/cash-transactions/{encryptedId}', [CashTransactionController::class, 'update'])->name('cash_transactions.update');
    Route::delete('/cash-transactions/{encryptedId}', [CashTransactionController::class, 'destroy'])->name('cash_transactions.destroy');
    Route::get('/contacts', [ContactAdminController::class, 'index'])->name('contacts.index');
    Route::get('/contacts/{encryptedId}', [ContactAdminController::class, 'show'])->name('contacts.show');
    Route::post('/contacts/{encryptedId}/reply', [ContactAdminController::class, 'reply'])->name('contacts.reply');
    Route::delete('/contacts/{encryptedId}', [ContactAdminController::class, 'destroy'])->name('contacts.destroy');
    Route::get('/donations', [DonationController::class, 'index'])->name('donations.index');
    Route::post('/donations', [DonationController::class, 'store'])->name('donations.store');
    Route::get('/donations/{encryptedId}', [DonationController::class, 'show'])->name('donations.show');
    Route::put('/donations/{encryptedId}', [DonationController::class, 'update'])->name('donations.update');
    Route::delete('/donations/{encryptedId}', [DonationController::class, 'destroy'])->name('donations.destroy');
    Route::get('/documents', [DocumentController::class, 'index'])->name('documents.index');
    Route::post('/documents', [DocumentController::class, 'store'])->name('documents.store');
    Route::get('/documents/{encryptedId}', [DocumentController::class, 'show'])->name('documents.show');
    Route::post('/documents/{encryptedId}', [DocumentController::class, 'update'])->name('documents.update.post');
    Route::put('/documents/{encryptedId}', [DocumentController::class, 'update'])->name('documents.update');
    Route::delete('/documents/{encryptedId}', [DocumentController::class, 'destroy'])->name('documents.destroy');
    Route::get('/fee-payments', [FeePaymentController::class, 'index'])->name('fee_payments.index');
    Route::post('/fee-payments', [FeePaymentController::class, 'store'])->name('fee_payments.store');
    Route::get('/fee-payments/{encryptedId}', [FeePaymentController::class, 'show'])->name('fee_payments.show');
    Route::put('/fee-payments/{encryptedId}', [FeePaymentController::class, 'update'])->name('fee_payments.update');
    Route::post('/fee-payments/{encryptedId}/validate', [FeePaymentController::class, 'validatePayment'])->name('fee_payments.validate');
    Route::post('/fee-payments/{encryptedId}/cancel', [FeePaymentController::class, 'cancel'])->name('fee_payments.cancel');
    Route::delete('/fee-payments/{encryptedId}', [FeePaymentController::class, 'destroy'])->name('fee_payments.destroy');
    Route::get('/statutes', [StatuteController::class, 'index'])->name('statutes.index');
    Route::post('/statutes', [StatuteController::class, 'store'])->name('statutes.store');
    Route::get('/statutes/{encryptedId}', [StatuteController::class, 'show'])->name('statutes.show');
    Route::put('/statutes/{encryptedId}', [StatuteController::class, 'update'])->name('statutes.update');
    Route::delete('/statutes/{encryptedId}', [StatuteController::class, 'destroy'])->name('statutes.destroy');
    Route::post('/statutes/{encryptedId}/titles', [StatuteTitleController::class, 'store'])->name('statute_titles.store');
    Route::put('/statute-titles/{encryptedId}', [StatuteTitleController::class, 'update'])->name('statute_titles.update');
    Route::delete('/statute-titles/{encryptedId}', [StatuteTitleController::class, 'destroy'])->name('statute_titles.destroy');
    Route::post('/statute-titles/{encryptedId}/articles', [StatuteArticleController::class, 'store'])->name('statute_articles.store');
    Route::put('/statute-articles/{encryptedId}', [StatuteArticleController::class, 'update'])->name('statute_articles.update');
    Route::delete('/statute-articles/{encryptedId}', [StatuteArticleController::class, 'destroy'])->name('statute_articles.destroy');
});
